# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "kensykora/windows_2012_r2_standard"

  config.vm.guest = :windows
  config.vm.communicator = "winrm"

  config.vm.network :forwarded_port, guest: 5985, host: 5985, id: "winrm", auto_correct: true
  config.vm.network :forwarded_port, guest: 80,   host: 8000, id: "web" # Port forward for IIS
  config.vm.network :forwarded_port, guest: 8443, host: 443,  id: "ssl" # Port forward for SSL IIS

  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--vram", "128"]
    v.gui = true
  end

  # Share folder
  #environment.host.capability(:create_smb_share) # Probably needs to be a :synced_folder plugin

  config.vm.provision "dsc" do |dsc|

    # Set of module paths relative to the Vagrantfile dir.
    #
    # These paths are added to the DSC Configuration running
    # environment to enable local modules to be addressed.
    #
    # @return [Array] Set of relative module paths.
    dsc.module_path = ["manifests"]

    # The path relative to `dsc.manifests_path` pointing to the Configuration file
    dsc.configuration_file  = "manifests/MyWebsite.ps1"

    # The Configuration Command to run. Assumed to be the same as the `dsc.configuration_file`
    # (sans extension) if not provided.
    dsc.configuration_name = "MyWebsite"

    # Commandline arguments to the Configuration run
    # Set of Parameters to pass to the DSC Configuration.
    dsc.configuration_params = {"-MachineName" => "localhost"}
  end
end